[0m03:25:13.194293 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x738093a5a570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x738093c1a780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x738093a58950>]}


============================== 03:25:13.214719 | 299f0219-6188-4b8b-a8a0-387cf2360bb4 ==============================
[0m03:25:13.214719 [info ] [MainThread]: Running with dbt=1.9.0
[0m03:25:13.218051 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init my_project', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m03:25:13.295449 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/root/.dbt')}
[0m03:25:13.298896 [info ] [MainThread]: Creating dbt configuration folder at 
[0m03:25:13.306907 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.12/site-packages/dbt/include/starter_project
[0m03:25:13.918098 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m03:25:13.921414 [info ] [MainThread]: Setting up your profile.
[0m03:27:11.424210 [info ] [MainThread]: Profile my_project written to /root/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m03:27:11.429359 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 110.2218, "process_in_blocks": "0", "process_kernel_time": 0.688881, "process_mem_max_rss": "92620", "process_out_blocks": "1472", "process_user_time": 2.746579}
[0m03:27:11.431799 [debug] [MainThread]: Command `dbt init` succeeded at 03:27:11.431618 after 110.22 seconds
[0m03:27:11.433943 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x738093d13320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7380936a9be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x738094344770>]}
[0m03:27:11.436061 [debug] [MainThread]: Flushing usage events
[0m03:27:13.065029 [debug] [MainThread]: An error was encountered while trying to flush usage events
